esphome:
  name: ice-temp-tilt
  friendly_name: Ice Temp Tilt

# Adafruit HUZZAH Breakout
esp8266:
  board: esp01_1m

# Enable logging
logger:

# Enable Home Assistant API
api:
  encryption:
    key: "SIgPdpW3eqAKreUiNUs3jUDrv+Xr3atgY9uVA2AUmWI="

ota:
  password: "5f571ed3a5aa1ce30324622721957613"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Ice-Temp-Tilt Fallback Hotspot"
    password: "C1y5NfqVrfkD"

captive_portal:
    
dallas:
  pin: 12
  update_interval: 10s

i2c:
  sda: 4
  scl: 5
  scan: true
  frequency: 10kHz

sensor:
  - platform: dallas
    name: Ice Bucket Temperature
    address: 0x173ce104571aab28
  - platform: mpu6050
    address: 0x68
    update_interval: 30s     
    accel_x:
      name: "MPU6050 Accel X"
    accel_y:
      name: "MPU6050 Accel Y"
    accel_z:
      name: "MPU6050 Accel z"

switch:
  platform: restart
  name: "Ice Temp Restart"